### ISSUE TITLE
main (0.1.8-alpha.1) fails to build and run

### ISSUE THREAD

**Issue by steflsd** [elizaOS/eliza-starter#113]
node v23.6.1

- Pulled the latest
- pnpm install (seems all good)
- pnpm build

```
pnpm build                                                                                                ok | 47s 

> @elizaos/eliza-starter@0.1.8-alpha.1 build /Users/steflsd/src/serova/eliza-starter
> tsup src/index.ts --format esm --dts

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
CLI Target: esnext
ESM Build start
ESM dist/index.js 27.48 KB
ESM ⚡️ Build success in 38ms
DTS Build start
src/index.ts(1,30): error TS2307: Cannot find module '@elizaos/client-direct' or its corresponding type declarations.
src/index.ts(8,8): error TS2307: Cannot find module '@elizaos/core' or its corresponding type declarations.
src/index.ts(9,33): error TS2307: Cannot find module '@elizaos/plugin-bootstrap' or its corresponding type declarations.
src/index.ts(10,34): error TS2307: Cannot find module '@elizaos/plugin-node' or its corresponding type declarations.
src/index.ts(11,30): error TS2307: Cannot find module '@elizaos/plugin-solana' or its corresponding type declarations.
src/index.ts(12,16): error TS2307: Cannot find module 'fs' or its corresponding type declarations.
src/index.ts(114,32): error TS2503: Cannot find namespace 'NodeJS'.
src/index.ts(167,27): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
src/index.ts(177,3): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

Error: error occurred in dts build
    at Worker.<anonymous> (/Users/steflsd/src/serova/eliza-starter/node_modules/.pnpm/tsup@8.3.5_postcss@8.5.1_typescript@5.6.3_yaml@2.7.0/node_modules/tsup/dist/index.js:1541:26)
    at Worker.emit (node:events:507:28)
    at MessagePort.<anonymous> (node:internal/worker:267:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
```

- pnpm start
```
pnpm start                                                                                                   1 err 

> @elizaos/eliza-starter@0.1.8-alpha.1 start /Users/steflsd/src/serova/eliza-starter
> tsc && node --loader ts-node/esm src/index.ts

src/cache/index.ts:2:80 - error TS2307: Cannot find module '@elizaos/core' or its corresponding type declarations.

2 import { CacheManager, Character, DbCacheAdapter, IDatabaseCacheAdapter } from "@elizaos/core";
                                                                                 ~~~~~~~~~~~~~~~

src/character.ts:1:73 - error TS2307: Cannot find module '@elizaos/core' or its corresponding type declarations.

1 import { Character, Clients, defaultCharacter, ModelProviderName } from "@elizaos/core";
                                                                          ~~~~~~~~~~~~~~~
...
(lots more)
src/index.ts:177:3 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

177   process.exit(1);
      ~~~~~~~


Found 31 errors in 7 files.

Errors  Files
     1  src/cache/index.ts:2
     1  src/character.ts:1
     5  src/chat/index.ts:1
     5  src/clients/index.ts:1
     5  src/config/index.ts:2
     5  src/database/index.ts:1
     9  src/index.ts:1
 ELIFECYCLE  Command failed with exit code 2.
```

I think the issue is that in
In the node_modules folder, we have @elizaos/core/.bin (with some bins) and package.json, but actually no source code...   

Daedalus:
$ git bisect bad
90957a558c0778656e6f26b74e87ab13b3eb00ad is the first bad commit

**Comment by steflsd** [comment]
Can confirm that the elizaos upstream package build was broken.

Pulled from npm - only contents.
tar xzvf elizaos-core-0.1.8-alpha.1.tgz 
x package/LICENSE
x package/package.json

**Comment by aminlatifi** [comment]
Dependencies can be found in the main eliza repo under eliza/packages/* are not well bundled to support typescript.

**Comment by creazy231** [comment]
Same problem over here

**Comment by caebwallace** [comment]
The packages deployed on npm in version 0.1.8-alpha.1 does not contains code : so it can not works ^^
https://www.npmjs.com/package/@elizaos/core?activeTab=code

**Comment by wtfsayo** [comment]
we upgraded to 0.1.9
